// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_create_token`, `_generate_with_sid`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

class NavojitClaims {
  final String sub;
  final String email;
  final String role;
  final String sid;
  final bool mfaV;
  final List<String> am;
  final String typ;
  final PlatformInt64 iat;
  final PlatformInt64 exp;

  const NavojitClaims({
    required this.sub,
    required this.email,
    required this.role,
    required this.sid,
    required this.mfaV,
    required this.am,
    required this.typ,
    required this.iat,
    required this.exp,
  });

  @override
  int get hashCode =>
      sub.hashCode ^
      email.hashCode ^
      role.hashCode ^
      sid.hashCode ^
      mfaV.hashCode ^
      am.hashCode ^
      typ.hashCode ^
      iat.hashCode ^
      exp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NavojitClaims &&
          runtimeType == other.runtimeType &&
          sub == other.sub &&
          email == other.email &&
          role == other.role &&
          sid == other.sid &&
          mfaV == other.mfaV &&
          am == other.am &&
          typ == other.typ &&
          iat == other.iat &&
          exp == other.exp;
}

class NavojitMobileAuth {
  final SovereignEnclave inner;

  const NavojitMobileAuth({required this.inner});

  Future<OmniTokens> generateTokens({
    required String userId,
    required String email,
    required String role,
  }) => RustLib.instance.api.crateApiNavojitMobileAuthGenerateTokens(
    that: this,
    userId: userId,
    email: email,
    role: role,
  );

  static Future<NavojitMobileAuth> newInstance({required String secret}) =>
      RustLib.instance.api.crateApiNavojitMobileAuthNewInstance(secret: secret);

  Future<OmniTokens> refreshTokens({required String refreshToken}) =>
      RustLib.instance.api.crateApiNavojitMobileAuthRefreshTokens(
        that: this,
        refreshToken: refreshToken,
      );

  Future<NavojitClaims> verifyToken({required String token}) => RustLib
      .instance
      .api
      .crateApiNavojitMobileAuthVerifyToken(that: this, token: token);

  @override
  int get hashCode => inner.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NavojitMobileAuth &&
          runtimeType == other.runtimeType &&
          inner == other.inner;
}

class OmniTokens {
  final String accessToken;
  final String refreshToken;
  final String sid;

  const OmniTokens({
    required this.accessToken,
    required this.refreshToken,
    required this.sid,
  });

  @override
  int get hashCode =>
      accessToken.hashCode ^ refreshToken.hashCode ^ sid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OmniTokens &&
          runtimeType == other.runtimeType &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          sid == other.sid;
}

class SovereignEnclave {
  final String secret;

  const SovereignEnclave({required this.secret});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SovereignEnclave> newInstance({required String secret}) =>
      RustLib.instance.api.crateApiSovereignEnclaveNew(secret: secret);

  @override
  int get hashCode => secret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SovereignEnclave &&
          runtimeType == other.runtimeType &&
          secret == other.secret;
}
