// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 630350362;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'navojit_auth',
        ioDirectory: '../navojit-auth-rs/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<OmniTokens> crateApiNavojitMobileAuthGenerateTokens({
    required NavojitMobileAuth that,
    required String userId,
    required String email,
    required String role,
  });

  Future<NavojitMobileAuth> crateApiNavojitMobileAuthNewInstance({
    required String secret,
  });

  Future<OmniTokens> crateApiNavojitMobileAuthRefreshTokens({
    required NavojitMobileAuth that,
    required String refreshToken,
  });

  Future<NavojitClaims> crateApiNavojitMobileAuthVerifyToken({
    required NavojitMobileAuth that,
    required String token,
  });

  Future<SovereignEnclave> crateApiSovereignEnclaveNew({
    required String secret,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<OmniTokens> crateApiNavojitMobileAuthGenerateTokens({
    required NavojitMobileAuth that,
    required String userId,
    required String email,
    required String role,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_navojit_mobile_auth(that, serializer);
          sse_encode_String(userId, serializer);
          sse_encode_String(email, serializer);
          sse_encode_String(role, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_omni_tokens,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNavojitMobileAuthGenerateTokensConstMeta,
        argValues: [that, userId, email, role],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNavojitMobileAuthGenerateTokensConstMeta =>
      const TaskConstMeta(
        debugName: "navojit_mobile_auth_generate_tokens",
        argNames: ["that", "userId", "email", "role"],
      );

  @override
  Future<NavojitMobileAuth> crateApiNavojitMobileAuthNewInstance({
    required String secret,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(secret, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_navojit_mobile_auth,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNavojitMobileAuthNewInstanceConstMeta,
        argValues: [secret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNavojitMobileAuthNewInstanceConstMeta =>
      const TaskConstMeta(
        debugName: "navojit_mobile_auth_new_instance",
        argNames: ["secret"],
      );

  @override
  Future<OmniTokens> crateApiNavojitMobileAuthRefreshTokens({
    required NavojitMobileAuth that,
    required String refreshToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_navojit_mobile_auth(that, serializer);
          sse_encode_String(refreshToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_omni_tokens,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNavojitMobileAuthRefreshTokensConstMeta,
        argValues: [that, refreshToken],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNavojitMobileAuthRefreshTokensConstMeta =>
      const TaskConstMeta(
        debugName: "navojit_mobile_auth_refresh_tokens",
        argNames: ["that", "refreshToken"],
      );

  @override
  Future<NavojitClaims> crateApiNavojitMobileAuthVerifyToken({
    required NavojitMobileAuth that,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_navojit_mobile_auth(that, serializer);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_navojit_claims,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNavojitMobileAuthVerifyTokenConstMeta,
        argValues: [that, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNavojitMobileAuthVerifyTokenConstMeta =>
      const TaskConstMeta(
        debugName: "navojit_mobile_auth_verify_token",
        argNames: ["that", "token"],
      );

  @override
  Future<SovereignEnclave> crateApiSovereignEnclaveNew({
    required String secret,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(secret, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sovereign_enclave,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSovereignEnclaveNewConstMeta,
        argValues: [secret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSovereignEnclaveNewConstMeta =>
      const TaskConstMeta(
        debugName: "sovereign_enclave_new",
        argNames: ["secret"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  NavojitMobileAuth dco_decode_box_autoadd_navojit_mobile_auth(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_navojit_mobile_auth(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  NavojitClaims dco_decode_navojit_claims(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return NavojitClaims(
      sub: dco_decode_String(arr[0]),
      email: dco_decode_String(arr[1]),
      role: dco_decode_String(arr[2]),
      sid: dco_decode_String(arr[3]),
      mfaV: dco_decode_bool(arr[4]),
      am: dco_decode_list_String(arr[5]),
      typ: dco_decode_String(arr[6]),
      iat: dco_decode_i_64(arr[7]),
      exp: dco_decode_i_64(arr[8]),
    );
  }

  @protected
  NavojitMobileAuth dco_decode_navojit_mobile_auth(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return NavojitMobileAuth(inner: dco_decode_sovereign_enclave(arr[0]));
  }

  @protected
  OmniTokens dco_decode_omni_tokens(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OmniTokens(
      accessToken: dco_decode_String(arr[0]),
      refreshToken: dco_decode_String(arr[1]),
      sid: dco_decode_String(arr[2]),
    );
  }

  @protected
  SovereignEnclave dco_decode_sovereign_enclave(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return SovereignEnclave(secret: dco_decode_String(arr[0]));
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  NavojitMobileAuth sse_decode_box_autoadd_navojit_mobile_auth(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_navojit_mobile_auth(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  NavojitClaims sse_decode_navojit_claims(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sub = sse_decode_String(deserializer);
    var var_email = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    var var_sid = sse_decode_String(deserializer);
    var var_mfaV = sse_decode_bool(deserializer);
    var var_am = sse_decode_list_String(deserializer);
    var var_typ = sse_decode_String(deserializer);
    var var_iat = sse_decode_i_64(deserializer);
    var var_exp = sse_decode_i_64(deserializer);
    return NavojitClaims(
      sub: var_sub,
      email: var_email,
      role: var_role,
      sid: var_sid,
      mfaV: var_mfaV,
      am: var_am,
      typ: var_typ,
      iat: var_iat,
      exp: var_exp,
    );
  }

  @protected
  NavojitMobileAuth sse_decode_navojit_mobile_auth(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_inner = sse_decode_sovereign_enclave(deserializer);
    return NavojitMobileAuth(inner: var_inner);
  }

  @protected
  OmniTokens sse_decode_omni_tokens(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_accessToken = sse_decode_String(deserializer);
    var var_refreshToken = sse_decode_String(deserializer);
    var var_sid = sse_decode_String(deserializer);
    return OmniTokens(
      accessToken: var_accessToken,
      refreshToken: var_refreshToken,
      sid: var_sid,
    );
  }

  @protected
  SovereignEnclave sse_decode_sovereign_enclave(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secret = sse_decode_String(deserializer);
    return SovereignEnclave(secret: var_secret);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_navojit_mobile_auth(
    NavojitMobileAuth self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_navojit_mobile_auth(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_navojit_claims(NavojitClaims self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sub, serializer);
    sse_encode_String(self.email, serializer);
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.sid, serializer);
    sse_encode_bool(self.mfaV, serializer);
    sse_encode_list_String(self.am, serializer);
    sse_encode_String(self.typ, serializer);
    sse_encode_i_64(self.iat, serializer);
    sse_encode_i_64(self.exp, serializer);
  }

  @protected
  void sse_encode_navojit_mobile_auth(
    NavojitMobileAuth self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sovereign_enclave(self.inner, serializer);
  }

  @protected
  void sse_encode_omni_tokens(OmniTokens self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.accessToken, serializer);
    sse_encode_String(self.refreshToken, serializer);
    sse_encode_String(self.sid, serializer);
  }

  @protected
  void sse_encode_sovereign_enclave(
    SovereignEnclave self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.secret, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
